const fs=require("fs");

console.log(`
=========================================
🚕 CABLINK BOOKRIDE TRUTH MIGRATION v1
=========================================
`);

const file="frontend/index.html";

if(!fs.existsSync(file)){
console.log("❌ frontend/index.html missing");
process.exit(1);
}

const backup=
"archive/frontend_cleanup/index_before_truth_bookride_"+Date.now()+".html";

fs.mkdirSync("archive/frontend_cleanup",{recursive:true});

fs.copyFileSync(file,backup);

console.log("✅ Backup created:",backup);


let html=fs.readFileSync(file,"utf8");


// Remove fake-looking simulate button

const oldButton=
'<button class="btn btn-outline" id="simBtn" onclick="bookRide()">� Simulate ride (test mode)</button>';

if(html.includes(oldButton)){

html=html.replace(
oldButton,
""
);

console.log("✅ Removed simulate ride button");

}else{

console.log("⚠️ Simulate button pattern not found");

}


// Replace direct fetch with truth bridge

const oldFetch=`const response = await fetch('/api/rides', {
      method: 'POST',
      headers: {'Content-Type':'application/json'},
      body: JSON.stringify(payload)
    });
    const data = await response.json();`;

const newFetch=`const data = await window.requestRealCabLinkRide(payload);`;


if(html.includes(oldFetch)){

html=html.replace(
oldFetch,
newFetch
);

console.log("✅ bookRide connected to truth bridge");

}else{

console.log("⚠️ Existing fetch block not found");
console.log("The code may already be migrated or formatted differently");

}


// Remove old random ride generator usage marker

html=html.replace(
"function generateRideId(){ return 'CL-' + Math.random().toString(36).substr(2,6).toUpperCase(); }",
"// Ride IDs now generated by backend"
);


if(!html.includes("CABLINK_BOOKRIDE_TRUTH_MIGRATION")){

html=
html.replace(
"<head>",
`<head>
<!-- CABLINK_BOOKRIDE_TRUTH_MIGRATION -->
`
);

}


fs.writeFileSync(file,html);

console.log(`
=========================================
✅ MIGRATION COMPLETE
=========================================

Next:
1. Restart Vite
2. Clear browser cache
3. Request a ride
4. Confirm CL-ID comes from backend

`);

