#!/usr/bin/env bash

set -e

echo "============================================================"
echo "CABLINK — CANONICAL DATA NORMALIZATION PLAN"
echo "============================================================"

echo
echo "This script is READ-ONLY."
echo "No files will be modified."
echo "No data will be migrated."

echo
echo "============================================================"
echo "1. LOWERCASE REQUESTED RIDES"
echo "============================================================"

node - <<'NODE'
const repo = require("./backend/canonical/ride_repository");

const rides = repo.all();

const affected = rides.filter(
    ride => ride.status === "requested"
);

console.log("Affected rides:", affected.length);

for (const ride of affected) {
    console.log({
        id: ride.id,
        currentStatus: ride.status,
        proposedStatus: "REQUESTED",
        pickup: ride.pickup,
        dropoff: ride.dropoff,
        fare: ride.fare,
        createdAt: ride.createdAt
    });
}
NODE

echo
echo "============================================================"
echo "2. ID FORMAT DISTRIBUTION"
echo "============================================================"

node - <<'NODE'
const repo = require("./backend/canonical/ride_repository");

const rides = repo.all();

for (const ride of rides) {
    const id = String(ride.id);

    let classification = "UNKNOWN";

    if (/^CL-[A-Z0-9]+$/.test(id)) {
        classification = "LEGACY_CL_ID";
    }

    if (/^RIDE-[0-9]+$/.test(id)) {
        classification = "CANONICAL_RIDE_ID";
    }

    console.log(
        id,
        "=>",
        classification
    );
}
NODE

echo
echo "============================================================"
echo "3. CANONICAL ENGINE NEW RIDE FORMAT"
echo "============================================================"

node - <<'NODE'
const engine = require("./backend/canonical/ride_engine");

console.log(
    "New ride IDs are generated by canonical engine."
);

console.log(
    "Expected prefix: RIDE-"
);

console.log(
    "Expected initial status:",
    engine.STATES.REQUESTED
);
NODE

echo
echo "============================================================"
echo "4. NORMALIZATION DECISION"
echo "============================================================"

cat <<'DECISION'

APPROVED NORMALIZATION POLICY:

1. Existing ride IDs are preserved.
2. CL-* IDs are treated as historical canonical records.
3. RIDE-* IDs remain the current canonical format.
4. New rides are created only by canonical/ride_engine.js.
5. New rides receive RIDE-* IDs.
6. Existing lowercase "requested" values are normalized to REQUESTED.
7. No ride is deleted.
8. No ride history is discarded.
9. No completed ride is modified.
10. No driver assignment is modified.
11. No financial data is modified.

DECISION

echo
echo "============================================================"
echo "NORMALIZATION PLAN COMPLETE"
echo "============================================================"

